[package]
name = "rust-toolchain-manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.26", features = [ "derive" ] }
thiserror = "1.0.37"
toml = "0.5.9"
